### ISSUE TITLE
Optional integration with the other Flysystem bundles

### ISSUE THREAD

**Issue by kbond** [kbond/filesystem#53]
- [league/flysystem-bundle](https://packagist.org/packages/league/flysystem-bundle)
- [oneup/flysystem-bundle](https://packagist.org/packages/oneup/flysystem-bundle)

This bundle can be configured with `adapter services`:

```yaml
zenstruck_filesystem:
    filesystems:
        public: '@=flysystem.adapter.service'
```

I'll have to see if the above bundles expose the underlying adapters as services. If not, I'm not sure how this would work.
