### ISSUE TITLE
[Bundle] `zenstruck_filesystem.filesystems.*.features` key

### ISSUE THREAD

**Issue by kbond** [kbond/filesystem#57]
```yaml
zenstruck_filesystem:
    filesystems:
        public:
            dsn: ...
            features:
                Zenstruck\Filesystem\Feature\SomeFeature: some.service
```
